name: Setup Python
description: Setup the python tools.

inputs:
  pipenv-version:
    description: Pipenv version to install
    required: false
    default: 2021.11.23
  python-version:
    description: Python version to install
    required: false
    default: 3.9

runs:
  using: "composite"
  steps:
    - run: |
        pipx install pipenv==${{ inputs.pipenv-version }}
      shell: bash
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
        cache: pipenv
        cache-dependency-path: Pipfile.lock
    - run: |
        pipenv install --dev
      shell: bash
