name: Setup Python
description: Setup the python tools.

inputs:
  pipenv-version:
    description: Pipenv version to install
    required: false
    default: 2021.11.23
  python-version:
    description: Python version to install
    required: false
    default: 3.9

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipenv==${{ inputs.pipenv-version }}
        pipenv install --dev --python=${{ inputs.pipenv-version }}
      shell: bash
